version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 11000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_HOME', 'https://<your_ip>/wordpress' );
        define( 'WP_SITEURL', 'https://<your_ip>/wordpress' );
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8-debian
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wordpress-root
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
